<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-Q1T02RD" failures="2" tests="2" name="Test(failed)" time="0.003" errors="0" timestamp="2022-06-01T01:06:42 IST">
  <testcase classname="com.TestNG08runFailedTC01.FailedTC01" name="testCase1" time="0.001">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at com.TestNG08runFailedTC01.FailedTC01.testCase1(FailedTC01.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.TestNG08runFailedTC01.FailedTestRunner.runFailedTC(FailedTestRunner.java:22)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="com.TestNG08runFailedTC01.FailedTC01" name="testCase2" time="0.001">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at com.TestNG08runFailedTC01.FailedTC01.testCase2(FailedTC01.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.TestNG08runFailedTC01.FailedTestRunner.runFailedTC(FailedTestRunner.java:22)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- Test(failed) -->
